# Generated by Django 5.2.11 on 2026-02-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('species', models.CharField(choices=[('dog', 'Cachorro'), ('cat', 'Gato'), ('all', 'Todos'), ('other', 'Outro')], default='all', max_length=20)),
                ('recommended_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
